version: '2'
services:
    db:
        image: mariadb:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            BIND-ADDRESS: 0.0.0.0
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
    php-apache:
        build: docker/php-apache
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/logs/symfony/:/var/www/app/logs
            - ./docker/logs/apache2/:/var/log/apache2
        links:
            - db
